development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fabrica_production

development_psql:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fabrica_development_psql
